Se agrega listado de coleccionistas
cgarciaa1/moviles-202215 pull request #60
Opened 2022-11-14 01:21 UTC by ID-Chacon

2022-11-14 22:25 UTC, cgarciaa1 requested changes

2022-11-14 22:25 UTC, cgarciaa1 commented on AppMovil202215/app/src/main/res/layout/collector_item.xml
> +                android:text="@{`Álbumes: ` + Integer.toString(collector.albumsCount)}"
En los XML no debe aparecer ningún string hard code

2022-11-15 00:46 UTC, ID-Chacon commented on AppMovil202215/app/src/main/res/layout/collector_item.xml
> +                android:text="@{`Álbumes: ` + Integer.toString(collector.albumsCount)}"
Se agrega commit con el cambio solicitado

2022-11-15 19:02 UTC, cgarciaa1 approved these changes

2022-11-15 19:03 UTC, merged