#HU04 - Detalle de artista.
cgarciaa1/moviles-202215 pull request #61
Opened 2022-11-14 14:07 UTC by andresmotiva

**Descripción:**
Se agrega visual de detalle de artista con información del mismo y listado de álbumes.

**Screenshots:**
![Screenshot 2022-11-14 at 9 07 01 AM](https://user-images.githubusercontent.com/60548499/201680403-8e8175c6-984b-4e80-90ac-847715d2a78c.png)

2022-11-14 22:16 UTC, cgarciaa1 requested changes

2022-11-14 22:16 UTC, cgarciaa1 commented on AppMovil202215/app/src/main/res/layout/detail_album_fragment.xml
> +    tools:context=".view.DetailArtistFragment">
¿Por qué cambiaste el archivo de detalle de álbumes?

2022-11-14 22:16 UTC, cgarciaa1 commented on AppMovil202215/app/src/main/res/layout/detail_artist_item.xml
> +<?xml version="1.0" encoding="utf-8"?>
Esto falla en tiempo de ejecución, al tocar un álbum del artista, la app se cierra

2022-11-14 22:16 UTC, cgarciaa1 commented on AppMovil202215/app/src/main/res/layout/detail_artist_item.xml
> +            android:text="@{artist_detail.birthDate}"
Mejorar esto:
- En la app aparece una fecha sin formato personalizado
- Debe aparecer un label que indique que es la fecha de nacimiento

2022-11-14 22:16 UTC, cgarciaa1 commented on AppMovil202215/app/src/main/res/menu/menu_bottom_nav.xml
> +        android:title="Artistas" />
¿por qué se realizó este cambio? en los XML no debe aparecer ningún string hard code

2022-11-15 01:10 UTC, andresmotiva commented on AppMovil202215/app/src/main/res/layout/detail_album_fragment.xml
> +    tools:context=".view.DetailArtistFragment">
Error de mi parte. Lo estaba usando como base para el de Artistas. Solucionado.

2022-11-15 01:40 UTC, andresmotiva commented on AppMovil202215/app/src/main/res/layout/detail_artist_item.xml
> +            android:text="@{artist_detail.birthDate}"
Buena idea. Ambas cosas fueron implementadas.

2022-11-15 02:28 UTC, andresmotiva commented on AppMovil202215/app/src/main/res/layout/detail_artist_item.xml
> +<?xml version="1.0" encoding="utf-8"?>
Finalmente era mas fácil duplicar el Adapter y eliminar la acción de dirigir al album.

2022-11-15 20:26 UTC, cgarciaa1 approved these changes

2022-11-15 20:27 UTC, merged